export CONFIG_MSM_MOORECHIP=m
export CONFIG_LEDS_SN3112=y
export CONFIG_LEDS_HTR3212=y
export CONFIG_JOYSTICK_MOORECHIP_JOYSTICK=y
export CONFIG_BACKLIGHT_AYN_MINILED=y
export CONFIG_FINGERPRINT_FOCALTECH=y
